###########################################################################
# Makefile for com.decafbad.memento
###########################################################################

APPID=com.decafbad.memento
VERSION=0.0.1

include main.mk
